export const spots = [
  {
    id: 1,
    name: "La Arena",
    distance: "7 km",
    image: require("../../assets/images/beach/la_arena.webp"),
    waveHeight: 1.2,
    wind: 12,
    direction: "NO",
    power: "Media",
    wavePeriod: 8,
  },
  {
    id: 2,
    name: "Sopelana",
    distance: "15 km",
    image: require("../../assets/images/beach/sopelana.webp"),
    waveHeight: 1.5,
    wind: 18,
    direction: "NO",
    power: "Alta",
    wavePeriod: 12,
  },
  {
    id: 3,
    name: "Mundaka",
    distance: "35 km",
    image: require("../../assets/images/beach/mundaka.webp"),
    waveHeight: 2.1,
    wind: 10,
    direction: "N",
    power: "Alta",
    wavePeriod: 15,
  },
  {
    id: 4,
    name: "Zarautz",
    distance: "55 km",
    image: require("../../assets/images/beach/zarautz.webp"),
    waveHeight: 0.8,
    wind: 22,
    direction: "O",
    power: "Baja",
    wavePeriod: 6,
  },
  {
    id: 5,
    name: "Somo",
    distance: "45 km",
    image: require("../../assets/images/beach/somo.webp"),
    waveHeight: 1.0,
    wind: 15,
    direction: "NO",
    power: "Media",
    wavePeriod: 8,
  },
];